config/routes.rb
Rails.application.routes.draw do
  get 'about/index'
  resources :players, only: %i[index show] do
    collection do
      get "search"
    end
  end

  resources :teams, only: %i[index show]
  resources :about, only: %i[index]

  root to: "home#index"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/college.rb
class College < ApplicationRecord
  has_many :players
  validates :name, presence: true, uniqueness: true
end

app/models/mascot.rb
class Mascot < ApplicationRecord
  belongs_to :team

  validates :name, presence: true
end

app/models/player.rb
class Player < ApplicationRecord
  # paginates_per 5
  belongs_to :college
  belongs_to :team
  has_many :positions

  validates :full_name, :games_played, :minutes, :points, :rebounds,
            :assists, :steals, :blocks, :turnovers, presence: true

  validates :points, :rebounds, :assists, :steals, :blocks, :turnovers, numericality: { only_integer: true }
end

app/models/player_position.rb
class PlayerPosition < ApplicationRecord
  belongs_to :player
  belongs_to :position
end

app/models/position.rb
class Position < ApplicationRecord
  has_many :players

  validates :name, presence: true, uniqueness: true
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :players
  has_one :mascot
  validates :name, presence: true, uniqueness: true

  def self.ordered_by_players
    self.select("teams.*")
        .select("COUNT(teams.id) as player_count")
        .left_joins(:players)
        .group("teams.id")
        .order("player_count DESC")
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @players = Player.includes(:team)
                     .order("points DESC")
                     .limit(10)

    @teams = Team.ordered_by_players
                 .limit(10)
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
    @players = Player.includes(:team).order("points DESC").page(params[:page])
  end

  def show
    @player = Player.find(params[:id])
  end
  # The @movie variable will be shared with :
  # app/views/movies/show.html.erb

  def search
    wildcard_search = "%#{params[:keywords]}%"
    @players = Player.where("full_name LIKE ?", wildcard_search)
  end
  # @movies variable will be shared with:
  # app/views/moves/search.html.erb
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index
    @teams = Team.ordered_by_players
  end

  def show
    @team = Team.find(params[:id])
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/about/index.html.erb
<h1 class="title is-1">About Page</h1>
<h3 class="title is-3">NBAStats_MidtermProject</h3>

<h4 class="title is-4">Description:</h4>
<p>
  I will be using 2 different data sets for this project.
  One is a set of data describing the individual players stats for the 2014-15 NBA season,
  and the other will be a list of team mascot names generated using the Faker gem.
  The NBA stats data set is in the CSV format and I will be using a seed script to populate my tables with the data from the .csv file.
  I will then create the mascot names using Faker.
  The tables in my project will include a Player table, a Team table, a College table, a Mascot table, a Position table and also a PlayerPosition table to deal with the many-to-many relationship between players and position.
  The different relationships in the table include:
</p>
<ol class="ml-5">
  <li>Player-Team = many-to-one</li>
  <li>Player-College = many-to-one</li>
  <li>Player-Position = many-to-many</li>
  <li>Mascot-Team = one-to-one</li>
</ol>

app/views/common/_footer.html.erb
<hr>
<footer>
  <p><em>CopyWrong NBA 2020</em></p>
  <ul class="mt-5">
    <li><%= link_to 'Home' , root_path %></li>
    <li><%= link_to 'Top Players', players_path %></li>
    <li><%= link_to 'Top Teams', teams_path %></li>
    <li><%= link_to 'About', about_index_path %></li>
  </ul>
</footer>

app/views/home/index.html.erb
<div class="columns">

  <div class="column">
    <h2 class="title is-4">Top Players</h2>
    <ol class="ml-5">
      <% @players.each do |player| %>
        <li>
          <%= link_to player.full_name, player %>
          <em>(<%= player.team.name %>)</em>
        </li>
      <% end %>
    </ol>
    <p class="mt-4">
      <strong>
        <%= link_to '🏀 See All Players 🏀', players_path %>
      </strong>
    </p>
  </div>

  <div class="column">
    <h2 class = "title is-4">Top 10 Teams</h2>
    <ol class="ml-5">
      <% @teams.each do |team| %>
        <li>
          <%= link_to team.name, team %>
          <em>(<%= pluralize team.player_count, "Player" %>)</em>
        </li>
      <% end %>
    </ol>
    <p class="mt-4">
      <strong>
        <%= link_to '🏀 See All Teams 🏀', teams_path %>
      </strong>
    </p>
  </div>



</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>NBA Stats Midterm Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <section class="section">
      <div class="container">
      <h1 class="title is-1"><%= link_to 'Top Players in 2014/15', root_path %></h1>

      <%= form_with(url: search_players_path, method: :get, local: true) do %>
        <div class="field is-grouped mb-5">
          <div class="control is-expanded">
            <%= text_field_tag(:keywords, nil, class: "input", placeholder: 'Search For Players') %>
          </div>
          <div class="control">
            <%= submit_tag("Search", class: "button is-primary") %>
          </div>
        </div>
      <% end %>

        <%= yield %>

        <%= render partial: 'common/footer' %>
      </div>
    </section>
  </body>
</html>

app/views/players/index.html.erb
<h2 class="title is-2">Top Players</h2>

<div>
  <%#<%= paginate(@players) %>
  <ol class="ml-5 mb-5">
    <% @players.each do |player|%>
      <li><%= link_to player.full_name, player %> plays for <%= player.team.name %>

      </li>
    <% end %>
  </ol>
  <%= paginate(@players)%>
</div>

app/views/players/search.html.erb
<p class="mb-5">Found <%= pluralize(@players.count, 'Player') %> when searching for: <%= params[:keywords] %></p>

<ul>
  <% @players.each do |player| %>
    <li><%= link_to player.full_name, player %></li>
  <% end %>
</ul>

app/views/players/show.html.erb
<h2 class="title is-2"><%= @player.full_name %></h2>

<p><strong>Team: </strong>
  <%= link_to @player.team.name, @player.team %>
</p>

<p>
  <strong>College: </strong>
  <%= @player.college.name %>
</p>

<p>
  <strong>Games Played: </strong>
  <%= @player.games_played %>
</p>

<p>
  <strong>Minutes: </strong>
  <%= @player.minutes %>
</p>

<p>
  <strong>Points: </strong>
  <%= @player.points %>
</p>

<p>
  <strong>Rebounds: </strong>
  <%= @player.rebounds %>
</p>

<p>
  <strong>Assists: </strong>
  <%= @player.assists %>
</p>

<p>
  <strong>Steals: </strong>
  <%= @player.steals %>
</p>

<p>
  <strong>Blocks: </strong>
  <%= @player.blocks %>
</p>

<p>
  <strong>Turnovers: </strong>
  <%= @player.turnovers %>
</p>

<p>
  <strong>Age: </strong>
  <%= @player.age %>
</p>

<p>
  <strong>Birth Place: </strong>
  <%= @player.birth_place %>
</p>

<p>
  <strong>Position: </strong>
  <%= @player.position %>
</p>